
# Service Identifiers
DEVICE_TO_DEVICE_SERVICE_ID = 0x01
ROUTER_TO_ROUTER_SERVICE_ID = 0x02
PROXY_SERVICE_ID = 0x03
LANE_SERVICE_ID = 0x04
CLIENT_SERVER_SERVICE_ID = 0x05

# Result Codes
SUCCESS = 0
NO_DEVICE_TO_DEVICE_SERVICE = 1
NO_ROUTER_TO_ROUTER_SERVICE = 2
NO_PROXY_SERVICE = 3
NO_LANE_SERVICE = 4
UNRECOGNIZED_SERVICE = 5
AUTHENTICATION_REQUIRED = 10  # authentication required
AUTHENTICATION_FAILURE = 11  # username and/or username/password failure
AUTHENTICATION_NO_SERVICE = 12  #
AUTHENTICATION_HASH = 13  # specified hash function not supported
